-- =========================================================
-- 006_payments.sql
-- Records HOW each walk-in bill was settled. Cash settles
-- immediately; UPI is "pending" until the OWNER confirms it
-- against his real UPI account. Payments can only be written
-- through the functions below, never directly from the app.
-- =========================================================

-- 0. the UPI ID customers pay into (owner-editable)
alter table settings add column if not exists upi_id text;

-- 1. payments table
create table payments (
  id          bigint generated by default as identity primary key,
  session_id  bigint references sessions (id),
  amount      numeric(10,2) not null,
  method      text not null check (method in ('cash','upi')),
  reference   text,
  status      text not null check (status in ('settled','pending','approved','rejected')),
  recorded_by uuid references auth.users (id) default auth.uid(),
  approved_by uuid references auth.users (id),
  created_at  timestamptz not null default now(),
  decided_at  timestamptz
);

alter table payments enable row level security;

-- staff can READ payments; there is NO insert/update policy, so the app
-- cannot write payments directly — only the functions below can.
create policy "Staff read payments" on payments for select to authenticated using (is_staff());

-- 2. record a payment for a walk-in bill
create or replace function record_payment(p_session_id bigint, p_method text, p_reference text default null)
returns bigint language plpgsql security definer set search_path = public as $$
declare
  v_amount numeric; v_status text; v_id bigint;
begin
  if not is_staff() then raise exception 'Not authorised'; end if;
  if p_method not in ('cash','upi') then raise exception 'Invalid payment method'; end if;

  select amount into v_amount
    from sessions where id = p_session_id and customer_type = 'walkin';
  if not found then raise exception 'Session not found'; end if;
  if v_amount is null then raise exception 'Session is not billed yet'; end if;

  if exists (select 1 from payments
             where session_id = p_session_id and status in ('settled','pending','approved')) then
    raise exception 'This session already has a payment';
  end if;

  if p_method = 'upi' then
    if p_reference is null or length(trim(p_reference)) = 0 then
      raise exception 'A UPI reference is required';
    end if;
    v_status := 'pending';
  else
    v_status := 'settled';
  end if;

  insert into payments (session_id, amount, method, reference, status)
    values (p_session_id, v_amount, p_method, nullif(trim(coalesce(p_reference,'')), ''), v_status)
    returning id into v_id;
  return v_id;
end; $$;

-- 3. owner approves or rejects a pending UPI payment
create or replace function approve_payment(p_payment_id bigint, p_approve boolean)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not is_owner() then raise exception 'Only the owner can approve payments'; end if;
  update payments
    set status = case when p_approve then 'approved' else 'rejected' end,
        approved_by = auth.uid(), decided_at = now()
    where id = p_payment_id and status = 'pending';
  if not found then raise exception 'Payment not found or already decided'; end if;
end; $$;

grant execute on function record_payment(bigint, text, text) to authenticated;
grant execute on function approve_payment(bigint, boolean)    to authenticated;
