-- 1. Create the table that holds your list of machines
create table pcs (
  id bigint generated by default as identity primary key,
  code text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- 2. Turn on the security lock for this table
alter table pcs enable row level security;

-- 3. Let anyone READ the list of PCs (the list isn't sensitive, and the
--    app needs to show it). No write rule means nobody can change the
--    roster through the app; you add or retire machines here in the dashboard.
create policy "Anyone can view PCs"
  on pcs for select
  using (true);

-- 4. Add your ten machines
insert into pcs (code) values
  ('PC-01'), ('PC-02'), ('PC-03'), ('PC-04'), ('PC-05'),
  ('PC-06'), ('PC-07'), ('PC-08'), ('PC-09'), ('PC-10');
