-- =========================================================
-- 002_create_sessions.sql
-- A "session" is one customer VISIT. A "segment" is one
-- stretch of time on one PC within that visit.
-- =========================================================

create table sessions (
  id            bigint generated by default as identity primary key,
  customer_type text not null check (customer_type in ('member', 'walkin')),
  customer_name text,
  member_id     bigint,
  started_at    timestamptz not null default now(),
  ended_at      timestamptz,
  created_at    timestamptz not null default now()
);

create table session_segments (
  id         bigint generated by default as identity primary key,
  session_id bigint not null references sessions (id),
  pc_id      bigint not null references pcs (id),
  started_at timestamptz not null default now(),
  ended_at   timestamptz,
  created_at timestamptz not null default now()
);

create unique index one_open_segment_per_pc
  on session_segments (pc_id)
  where ended_at is null;

create unique index one_open_segment_per_session
  on session_segments (session_id)
  where ended_at is null;

alter table sessions          enable row level security;
alter table session_segments  enable row level security;

create policy "Staff read sessions"   on sessions for select to authenticated using (true);
create policy "Staff create sessions" on sessions for insert to authenticated with check (true);
create policy "Staff update sessions" on sessions for update to authenticated using (true) with check (true);

create policy "Staff read segments"   on session_segments for select to authenticated using (true);
create policy "Staff create segments" on session_segments for insert to authenticated with check (true);
create policy "Staff update segments" on session_segments for update to authenticated using (true) with check (true);
